<div class="page-header">
    <h1>Index de Articulos</h1>
</div>

<?php
echo $this->tag->linkTo(["article/create", "Agregar un articulo!", 'class' => 'btn btn-primary']);
?>
  <p><?=$this->flashSession->output() ?></p>


<?php
if ($articles->count() > 0) {
?>
     <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th>#</th>
                <th>Name del Articulo</th>
                <th>Description Del Articulo</th>
                <th>Action</th>

            </tr>
        </thead>
        <tfoot>
            <tr>
                <td colspan="3">Users quantity: <?php echo $articles->count(); ?></td>
            </tr>
        </tfoot>
        <tbody>
            <?php foreach ($articles as $article) { ?>
                <tr>
                    <td><?php echo $article->id; ?></td>
                    <td><?php echo $article->nameArticle; ?></td>
                    <td><?php echo $article->descriptionArticle; ?></td>
                    <td>
                    <?php
                    echo $this->tag->linkTo(["article/edit/".$article->id, "Editar", 'class' => 'btn btn-outline-info','title'=>'Editar']);
                    echo '&nbsp';
                    echo $this->tag->linkTo(["article/delete/".$article->id, "Eliminar", 'class' => 'btn btn-outline-danger','title'=>'Eliminar']);
                    ?>
                    </td>
                </tr>

            <?php } ?>
        </tbody>
    </table>
<?php
}
?>